apiVersion: 1
prune: true

datasources:
  - name: Analytics PostgreSQL
    uid: analytics-postgres
    type: postgres
    access: proxy
    url: analytics_db:5432
    user: analytics
    secureJsonData:
      password: analytics
    jsonData:
      database: analytics
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      connMaxLifetime: 14400
      maxIdleConns: 10
      maxOpenConns: 100
